// <auto-generated />
using System;
using AMM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMM.Infrastructure.Migrations
{
    [DbContext(typeof(AmmDbContext))]
    [Migration("20260621162501_AddDireccionObjetoInterventorCenso")]
    partial class AddDireccionObjetoInterventorCenso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMM.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MicroterritorioId")
                        .HasColumnType("int")
                        .HasColumnName("microterritorio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("MicroterritorioId");

                    b.ToTable("AREA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Censo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<short?>("DepartamentoId")
                        .HasColumnType("smallint")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Geolocalizacion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("geolocalizacion");

                    b.Property<string>("Microterritorio")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("microterritorio");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int")
                        .HasColumnName("municipio_id");

                    b.Property<string>("ObjetoInterventor")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("objeto_interventor");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacion");

                    b.Property<string>("Territorio")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("territorio");

                    b.Property<byte>("TipoEntornoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo_entorno_id");

                    b.Property<int?>("TotalMiembros")
                        .HasColumnType("int")
                        .HasColumnName("total_miembros");

                    b.Property<long?>("UbicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ubicacion_id");

                    b.Property<int?>("VisitantesTemporalesCol")
                        .HasColumnType("int")
                        .HasColumnName("visitantes_temporales_col");

                    b.Property<int?>("VisitantesTemporalesMig")
                        .HasColumnType("int")
                        .HasColumnName("visitantes_temporales_mig");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("TipoEntornoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("CENSO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.CensoNovedad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CensoId")
                        .HasColumnType("bigint")
                        .HasColumnName("censo_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacion");

                    b.Property<long?>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<byte?>("PresenciaNovedadId")
                        .HasColumnType("tinyint")
                        .HasColumnName("presencia_novedad_id");

                    b.Property<byte>("TipoNovedadId")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo_novedad_id");

                    b.Property<long?>("TratamientoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tratamiento_id");

                    b.HasKey("Id");

                    b.HasIndex("CensoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PresenciaNovedadId");

                    b.HasIndex("TipoNovedadId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("CENSO_NOVEDAD", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.CensoPersona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CensoId")
                        .HasColumnType("bigint")
                        .HasColumnName("censo_id");

                    b.Property<string>("Comunidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("comunidad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<bool>("EsJefeHogar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_jefe_hogar");

                    b.Property<byte>("EstadoPersonaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado_persona_id");

                    b.Property<string>("GrupoPoblacionEspecial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("grupo_poblacion_especial");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<byte?>("ParentescoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("parentesco_id");

                    b.HasKey("Id");

                    b.HasIndex("CensoId");

                    b.HasIndex("EstadoPersonaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ParentescoId");

                    b.ToTable("CENSO_PERSONA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Departamento", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("CodigoDane")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigoDANE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("departamento");

                    b.HasKey("Id");

                    b.ToTable("DEPARTAMENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Enfermedad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ENFERMEDAD", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Estado", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ESTADO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EstadoPersona", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ESTADO_PERSONA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EstadoUsuario", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ESTADO_USUARIO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Etnia", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasDefaultValue("")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("ETNIA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EtniaPuebloIndigena", b =>
                {
                    b.Property<byte>("EtniaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("etnia_id");

                    b.Property<short>("PuebloIndigenaId")
                        .HasColumnType("smallint")
                        .HasColumnName("pueblo_indigena_id");

                    b.HasKey("EtniaId", "PuebloIndigenaId");

                    b.HasIndex("PuebloIndigenaId");

                    b.ToTable("ETNIA_PUEBLO_INDIGENA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.Property<byte>("EventoTipoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha_evento");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EventoTipoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("EVENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoEscabiosis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Localizacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("localizacion");

                    b.Property<byte?>("Severidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("severidad");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_ESCABIOSIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoGeohelmintiasis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Resultado")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("resultado");

                    b.Property<string>("TipoPrueba")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("tipo_prueba");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_GEOHELMINTIASIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoLeshmaniasisCutanea", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("TipoLesion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_lesion");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_LEISHMANIASIS_CUTANEA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoMalaria", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Especie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("especie");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_MALARIA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoPediculosis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<byte?>("Grado")
                        .HasColumnType("tinyint")
                        .HasColumnName("grado");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_PEDICULOSIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoPian", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Estadio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estadio");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_PIAN", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTeniasisCisticercosis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<bool?>("Cisticercosis")
                        .HasColumnType("bit")
                        .HasColumnName("cisticercosis");

                    b.Property<bool?>("Teniasis")
                        .HasColumnType("bit")
                        .HasColumnName("teniasis");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_TENIASIS_CISTICERCOSIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTipo", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("EVENTO_TIPO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTracoma", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<int?>("CriterioExclusionId")
                        .HasColumnType("int")
                        .HasColumnName("criterio_exclusion_id");

                    b.Property<bool?>("ExaminadoTt")
                        .HasColumnType("bit")
                        .HasColumnName("examinado_tt");

                    b.Property<string>("OpacidadCorneal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("opacidad_corneal");

                    b.Property<byte?>("Triquiasis")
                        .HasColumnType("tinyint")
                        .HasColumnName("triquiasis");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_TRACOMA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTuberculosis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("TipoTuberculosis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_tuberculosis");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_TUBERCULOSIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTuberculosisContacto", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacion");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_TUBERCULOSIS_CONTACTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTungiasis", b =>
                {
                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<string>("Complicaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("complicaciones");

                    b.Property<int?>("NumeroLesiones")
                        .HasColumnType("int")
                        .HasColumnName("numero_lesiones");

                    b.HasKey("EventoId");

                    b.ToTable("EVENTO_TUNGIASIS", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.FormaFarmaceutica", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("FORMA_FARMACEUTICA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCum")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_cum");

                    b.Property<string>("Concentracion")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("concentracion");

                    b.Property<short>("FormaFarmaceuticaId")
                        .HasColumnType("smallint")
                        .HasColumnName("forma_farmaceutica_id");

                    b.Property<string>("NombreGenerico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_generico");

                    b.HasKey("Id");

                    b.HasIndex("FormaFarmaceuticaId");

                    b.ToTable("MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ruta");

                    b.HasKey("Id");

                    b.ToTable("MENU", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Microterritorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("TerritorioId")
                        .HasColumnType("int")
                        .HasColumnName("territorio_id");

                    b.HasKey("Id");

                    b.HasIndex("TerritorioId");

                    b.ToTable("MICROTERRITORIO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.MotivoNoTratamiento", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("MOTIVO_NO_TRATAMIENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDaneDpto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoDANE_Dpto");

                    b.Property<short>("DepartamentoId")
                        .HasColumnType("smallint")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("municipio");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("MUNICIPIO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("documento");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<byte?>("PertenenciaEtnicaId")
                        .HasColumnType("tinyint")
                        .HasColumnName("pertenencia_etnica_id");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("primer_nombre");

                    b.Property<short?>("PuebloIndigenaId")
                        .HasColumnType("smallint")
                        .HasColumnName("pueblo_indigena_id");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("segundo_nombre");

                    b.Property<byte>("SexoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("sexo_id");

                    b.Property<byte>("TipoDocumentoId")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PertenenciaEtnicaId");

                    b.HasIndex("PuebloIndigenaId");

                    b.HasIndex("SexoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("PACIENTE", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Parentesco", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("PARENTESCO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("PERMISO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.PersonaEnfermedad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CensoPersonaId")
                        .HasColumnType("bigint")
                        .HasColumnName("censo_persona_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<byte>("EnfermedadId")
                        .HasColumnType("tinyint")
                        .HasColumnName("enfermedad_id");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.HasKey("Id");

                    b.HasIndex("CensoPersonaId");

                    b.HasIndex("EnfermedadId");

                    b.HasIndex("EstadoId");

                    b.ToTable("PERSONA_ENFERMEDAD", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.PresenciaNovedad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("PRESENCIA_NOVEDAD", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Prm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<byte?>("Severidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("severidad");

                    b.Property<long>("TratamientoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tratamiento_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("PRM", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.PuebloIndigena", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("PUEBLO_INDIGENA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Rafa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("EnlaceReporteInvima")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("enlace_reporte_invima");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_evento");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("paciente_id");

                    b.Property<byte?>("Severidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("severidad");

                    b.Property<string>("Sintomas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sintomas");

                    b.Property<long>("TratamientoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tratamiento_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("RAFA", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Sexo", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("SEXO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Territorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("TERRITORIO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("TIPO_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.TipoEntorno", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("TIPO_ENTORNO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.TipoNovedad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("TIPO_NOVEDAD", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.TipoSupervision", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("TIPO_SUPERVISION", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Tratamiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<byte>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("estado_id");

                    b.Property<long>("EventoId")
                        .HasColumnType("bigint")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<short?>("MotivoNoTratamientoId")
                        .HasColumnType("smallint")
                        .HasColumnName("motivo_no_tratamiento_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacion");

                    b.Property<bool>("RequiereTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("requiere_tratamiento");

                    b.Property<int?>("SupervisadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisado_por_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("MotivoNoTratamientoId");

                    b.HasIndex("SupervisadoPorId");

                    b.ToTable("TRATAMIENTO", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.TratamientoDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Dosis")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("dosis");

                    b.Property<short?>("FormaFarmaceuticaId")
                        .HasColumnType("smallint")
                        .HasColumnName("forma_farmaceutica_id");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int")
                        .HasColumnName("medicamento_id");

                    b.Property<byte?>("SupervisionId")
                        .HasColumnType("tinyint")
                        .HasColumnName("supervision_id");

                    b.Property<long>("TratamientoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tratamiento_id");

                    b.Property<string>("Via")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("via");

                    b.HasKey("Id");

                    b.HasIndex("FormaFarmaceuticaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("SupervisionId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("TRATAMIENTO_DETALLE", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<double?>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("float")
                        .HasColumnName("lon");

                    b.HasKey("Id");

                    b.ToTable("UBICACION", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AzureAdObjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("azure_ad_object_id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creado_por");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int")
                        .HasColumnName("entidad_id");

                    b.Property<byte>("EstadoUsuarioId")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado_usuario_id");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("modificado_en");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("EstadoUsuarioId");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("ROL_MENU", b =>
                {
                    b.Property<int>("rol_id")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("menu_id")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.HasKey("rol_id", "menu_id");

                    b.HasIndex("menu_id");

                    b.ToTable("ROL_MENU", (string)null);
                });

            modelBuilder.Entity("ROL_PERMISO", b =>
                {
                    b.Property<int>("rol_id")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("permiso_id")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.HasKey("rol_id", "permiso_id");

                    b.HasIndex("permiso_id");

                    b.ToTable("ROL_PERMISO", (string)null);
                });

            modelBuilder.Entity("USUARIO_ROL", b =>
                {
                    b.Property<int>("usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("rol_id")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("usuario_id", "rol_id");

                    b.HasIndex("rol_id");

                    b.ToTable("USUARIO_ROL", (string)null);
                });

            modelBuilder.Entity("AMM.Domain.Entities.Area", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Microterritorio", "Microterritorio")
                        .WithMany()
                        .HasForeignKey("MicroterritorioId")
                        .IsRequired();

                    b.Navigation("Microterritorio");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Censo", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.HasOne("AMM.Domain.Entities.TipoEntorno", "TipoEntorno")
                        .WithMany()
                        .HasForeignKey("TipoEntornoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");

                    b.Navigation("Departamento");

                    b.Navigation("Estado");

                    b.Navigation("Municipio");

                    b.Navigation("TipoEntorno");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("AMM.Domain.Entities.CensoNovedad", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Censo", "Censo")
                        .WithMany("Novedades")
                        .HasForeignKey("CensoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId");

                    b.HasOne("AMM.Domain.Entities.PresenciaNovedad", "PresenciaNovedad")
                        .WithMany()
                        .HasForeignKey("PresenciaNovedadId");

                    b.HasOne("AMM.Domain.Entities.TipoNovedad", "TipoNovedad")
                        .WithMany()
                        .HasForeignKey("TipoNovedadId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId");

                    b.Navigation("Censo");

                    b.Navigation("Estado");

                    b.Navigation("Paciente");

                    b.Navigation("PresenciaNovedad");

                    b.Navigation("TipoNovedad");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.CensoPersona", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Censo", "Censo")
                        .WithMany("Personas")
                        .HasForeignKey("CensoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.EstadoPersona", "EstadoPersona")
                        .WithMany()
                        .HasForeignKey("EstadoPersonaId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Parentesco", "Parentesco")
                        .WithMany()
                        .HasForeignKey("ParentescoId");

                    b.Navigation("Censo");

                    b.Navigation("EstadoPersona");

                    b.Navigation("Paciente");

                    b.Navigation("Parentesco");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EtniaPuebloIndigena", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Etnia", "Etnia")
                        .WithMany()
                        .HasForeignKey("EtniaId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.PuebloIndigena", "PuebloIndigena")
                        .WithMany()
                        .HasForeignKey("PuebloIndigenaId")
                        .IsRequired();

                    b.Navigation("Etnia");

                    b.Navigation("PuebloIndigena");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Evento", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.EventoTipo", "EventoTipo")
                        .WithMany()
                        .HasForeignKey("EventoTipoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("EventoTipo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoEscabiosis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoGeohelmintiasis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoLeshmaniasisCutanea", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoMalaria", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoPediculosis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoPian", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTeniasisCisticercosis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTracoma", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTuberculosis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTuberculosisContacto", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.EventoTungiasis", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("AMM.Domain.Entities.FormaFarmaceutica", "FormaFarmaceutica")
                        .WithMany()
                        .HasForeignKey("FormaFarmaceuticaId")
                        .IsRequired();

                    b.Navigation("FormaFarmaceutica");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Microterritorio", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Territorio", "Territorio")
                        .WithMany()
                        .HasForeignKey("TerritorioId")
                        .IsRequired();

                    b.Navigation("Territorio");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Etnia", "PertenenciaEtnica")
                        .WithMany()
                        .HasForeignKey("PertenenciaEtnicaId");

                    b.HasOne("AMM.Domain.Entities.PuebloIndigena", "PuebloIndigena")
                        .WithMany()
                        .HasForeignKey("PuebloIndigenaId");

                    b.HasOne("AMM.Domain.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("PertenenciaEtnica");

                    b.Navigation("PuebloIndigena");

                    b.Navigation("Sexo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.PersonaEnfermedad", b =>
                {
                    b.HasOne("AMM.Domain.Entities.CensoPersona", "CensoPersona")
                        .WithMany("Enfermedades")
                        .HasForeignKey("CensoPersonaId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Enfermedad", "Enfermedad")
                        .WithMany()
                        .HasForeignKey("EnfermedadId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.Navigation("CensoPersona");

                    b.Navigation("Enfermedad");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Prm", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId")
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Rafa", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId")
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Territorio", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Tratamiento", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.MotivoNoTratamiento", "MotivoNoTratamiento")
                        .WithMany()
                        .HasForeignKey("MotivoNoTratamientoId");

                    b.HasOne("AMM.Domain.Entities.Usuario", "SupervisadoPor")
                        .WithMany()
                        .HasForeignKey("SupervisadoPorId");

                    b.Navigation("Estado");

                    b.Navigation("Evento");

                    b.Navigation("MotivoNoTratamiento");

                    b.Navigation("SupervisadoPor");
                });

            modelBuilder.Entity("AMM.Domain.Entities.TratamientoDetalle", b =>
                {
                    b.HasOne("AMM.Domain.Entities.FormaFarmaceutica", "FormaFarmaceutica")
                        .WithMany()
                        .HasForeignKey("FormaFarmaceuticaId");

                    b.HasOne("AMM.Domain.Entities.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.TipoSupervision", "Supervision")
                        .WithMany()
                        .HasForeignKey("SupervisionId");

                    b.HasOne("AMM.Domain.Entities.Tratamiento", "Tratamiento")
                        .WithMany("Detalles")
                        .HasForeignKey("TratamientoId")
                        .IsRequired();

                    b.Navigation("FormaFarmaceutica");

                    b.Navigation("Medicamento");

                    b.Navigation("Supervision");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AMM.Domain.Entities.EstadoUsuario", "EstadoUsuario")
                        .WithMany()
                        .HasForeignKey("EstadoUsuarioId")
                        .IsRequired();

                    b.Navigation("EstadoUsuario");
                });

            modelBuilder.Entity("ROL_MENU", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Menu", null)
                        .WithMany()
                        .HasForeignKey("menu_id")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .IsRequired();
                });

            modelBuilder.Entity("ROL_PERMISO", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("permiso_id")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .IsRequired();
                });

            modelBuilder.Entity("USUARIO_ROL", b =>
                {
                    b.HasOne("AMM.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .IsRequired();

                    b.HasOne("AMM.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .IsRequired();
                });

            modelBuilder.Entity("AMM.Domain.Entities.Censo", b =>
                {
                    b.Navigation("Novedades");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("AMM.Domain.Entities.CensoPersona", b =>
                {
                    b.Navigation("Enfermedades");
                });

            modelBuilder.Entity("AMM.Domain.Entities.Tratamiento", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
